Announcement notification
manifoldmarkets/manifold pull request #1904
Opened 2023-07-17 18:29 UTC by SirSaltyy

2023-07-17 18:36 UTC, SirSaltyy commented
Fyi I am unable to test the code locally because of an unknown error me and Ian couldn't figure out (although Ian was able to test it on his system). Not sure if deployment failed due to the site-wide outages or something wrong with my code haha

2023-07-17 23:29 UTC, IanPhilips requested changes
Great work Salty! This will be super nice to be able to let our users know of important changes! You've shown great perseverance getting this so close to the finish line :).

2023-07-17 23:29 UTC, IanPhilips commented on backend/api/src/create-announcement.ts
> +const firestore = admin.firestore()
What is this used for?

2023-07-17 23:29 UTC, IanPhilips commented on backend/api/src/create-announcement.ts
> +      `select data from users limit $1 offset $2`,
I think it's good to have an `orderBy` in the query so that the offset searches over the same exact query pages.

2023-07-17 23:29 UTC, IanPhilips commented on backend/api/src/create-announcement.ts
> +  if (!isAdmin) throw new APIError(403, 'Insufficient permissions.')
you can put this error before the validation, even.

2023-07-17 23:29 UTC, IanPhilips commented on backend/api/src/create-announcement.ts
> +  if (!isAdmin) throw new APIError(403, 'Insufficient permissions.')
And put the isAdmin code before the `const pg = createSupabaseDirectClient()` line

2023-07-17 23:29 UTC, IanPhilips commented on backend/shared/src/create-notification.ts
> +    data: { url },
it's nice imo to tie the data to the type, e.g.:
`{url} as AnnouncementData`

2023-07-17 23:29 UTC, IanPhilips commented on backend/shared/src/create-notification.ts
> +  const pg = createSupabaseDirectClient()
Don't you have to check somewhere if they've opted out of browser notifications? See the line `if (userOptedOutOfBrowserNotifications(privateUser)) return` from just above your function.

2023-07-17 23:29 UTC, IanPhilips commented on web/components/notifications/notification-types.tsx
> +        announcement ? (
sourceText is nonoptional

2023-07-17 23:29 UTC, IanPhilips commented on web/components/notifications/notification-types.tsx
> +          <UserLink
Why does display of the UserLink depend on the announcement data having a url?

2023-07-17 23:29 UTC, IanPhilips commented on web/pages/notifications.tsx
> +  if (isAdmin) {
you can use `buildArray()` for this, checking if `isAdmin && {
      title: 'Send Notif',
      content: <SendCustomNotification />,
    }` in the array

2023-07-17 23:29 UTC, IanPhilips commented on web/pages/notifications.tsx
> +  const { isSubmitting, disabled, onSubmit, color, size, title } = props
A screenshot of this flow would be nice to attach to this PR.

2023-12-29 03:15 UTC, sipec commented
This PR has been open for 6 months now
I think this is a good feature but we should probably close this PR and reassign to someone ...

2025-09-15 19:01 UTC, closed without merging