Change calibration calculation to exclude implicit redemption sales in addition to explicit sales
manifoldmarkets/manifold pull request #2465
Opened 2024-02-13 22:46 UTC by jacyanthis

2024-02-13 22:47 UTC, jacyanthis commented
This PR reflects what seems to be consensus on how calibration should be calculated in [the Discord thread](https://discord.com/channels/915138780216823849/1192249627790028945).

2024-02-16 02:12 UTC, akrolsmir commented
Requesting @mantikoros to take a look, as the person who did the calibration calculations!

2024-02-20 01:11 UTC, mantikoros requested changes
The position calculation should use shares, not mana amounts.

2024-02-20 01:11 UTC, mantikoros commented on web/pages/[username]/calibration.tsx
> +    for (const bet of bets.reverse() as Bet[]) {
.reverse() is a mutable method, which could lead to subtle errors in the future. Prefer .slice().reverse()

2024-02-20 01:11 UTC, mantikoros commented on web/pages/[username]/calibration.tsx
> +      const nextPosition = currentPosition + bet.amount * betSign
Position calculation is wrong. It should use shares, not mana amounts (which is what bet.amount is)

2024-02-20 01:11 UTC, mantikoros commented on web/pages/[username]/calibration.tsx
> +        const w = bet.amount
should be consistent and use # of shares

2024-02-21 12:41 UTC, jacyanthis commented
Thanks, @mantikoros! I replaced `bet.reverse()` with out-of-place `bet.slice().reverse()` and `bet.amount` with `bet.shares` (assuming that means what I think it means; excluding the `bet.amount < 0` preexisting explicit sale check) as well as an unrelated fix to the incorrect scope of `w`. Of course it should still be tested by someone who can do that.

2024-02-22 03:18 UTC, mantikoros commented on web/pages/[username]/calibration.tsx
> +        w = nextPosition
This should be the abs value of next pos; the weight should always be positive.

Other than that, it looks good. I'll make this fix and merge it in...soon...

2024-02-22 18:43 UTC, mantikoros approved these changes
Thanks for the contribution!

2024-02-22 18:44 UTC, merged