Implement really obvious optimizations on `placebet`, `sellbet`, `sellshares`
manifoldmarkets/manifold pull request #452
Opened 2022-06-07 21:56 UTC by mqp

Just picking the lowest possible hanging fruit here. After this `placebet` (e.g.) will basically be doing what looks like a conceptually reasonable thing from a performance standpoint, so then we can take a look at the graphs, see where we stand, and judge whether we want to spend more effort.

- It turns out that most API endpoints that want user info are gonna want it in a transaction anyway, so looking it up in the auth flow is not a good idea because it's wasted work.
- There was no reason for `redeemShares` to be happening in a separate transaction and re-looking-up stuff that was already looked up.

2022-06-07 22:04 UTC, mqp commented
It's possible that if we were smarter at using Firestore we could do some of this work without wrapping everything in a transaction, but it's definitely not "really obvious" to me how to do it.

2022-06-10 05:02 UTC, mantikoros requested changes
There's an issue with redeemShares over-writing a previously set user balance. But other than that, everything else looks good to me!

2022-06-10 06:21 UTC, mqp commented on functions/src/redeem-shares.ts
> +  trans.update(userSnap.ref, { balance: newBalance })
Wow, that's a good point, let me think about that.

2022-06-11 00:40 UTC, mqp commented
On reflection, I think I can improve the redemption part, but it requires more thought, so I just killed it for now and we can merge the rest of this stuff without going down a redemption rabbit hole at this moment.

2022-06-11 00:40 UTC, mqp commented on functions/src/redeem-shares.ts
> +  trans.update(userSnap.ref, { balance: newBalance })
Tabled this for now.

2022-06-11 00:51 UTC, merged