Refinement of LiteMarket
manifoldmarkets/manifold pull request #479
Opened 2022-06-10 19:27 UTC by TrueMilli

@wasabipesto noticed inconsistencies in the market data the api returns.

I've taken a look at LiteMarket, my suggestions are in this PR.
There is more data for non-binary markets now and hopefully it's clearer what the values mean.
All info that was in the LiteMarket before is still in it, there has been some reshuffling tho. 

### Details
* pool: set in the same way as in the "Market Overview" from contract-info-dialog.tsx now
* totalShares: a new field containing the total number of shares of the contract. The value is equal to the old "pool" value for binary markets
* removal of totalLiquidity: was only set for binary markets and its value was identical to the new totalShares in that case

This does not need to be merged right away but can serve as basis for discussion.

2022-06-13 16:14 UTC, jahooma reviewed
Thanks, it does seem like we could be providing better info to the api!

2022-06-14 01:01 UTC, mantikoros requested changes
Looks okay except for contractPool formatting.

2022-06-14 07:09 UTC, TrueMilli commented on web/lib/firebase/contracts.ts
> +    ? 'Empty Pool'
It wanted to keep behaviour as it was before:

Previous version:
```
export function getPoolValue(contract: Contract) {
  return contract.mechanism === 'cpmm-1'
    ? formatMoney(contract.totalLiquidity)
    : contract.mechanism === 'dpm-2'
    ? formatMoney(sum(Object.values(contract.pool)))
    : 'Empty pool'
}

2022-06-14 16:59 UTC, mantikoros approved these changes

2022-06-14 17:01 UTC, merged

2022-06-14 17:06 UTC, mantikoros commented
Had to revert this because of static type checking issues.

2022-06-14 17:10 UTC, mantikoros commented
I also now think this PR may be unwise. Our API uses versioning. We really shouldn't make any breaking changes without incrementing the version. When we're ready to release the next version of our API, we can incorporate these changes.

2022-06-14 17:16 UTC, wasabipesto commented
I consider this PR to be two different things:
1. Fixing a bug, that `pool` was broken for free-response markets (13% of all markets)
2. Removing `totalLiquidity`, a property with questionable usefulness

As a user of the API, I would really really like (1) to be fixed ASAP. I don't use `totalLiquidity` anymore, so if that's the only part justifying the version bump we can hold on part (2).