Inga/prettier embed
manifoldmarkets/manifold pull request #989
Opened 2022-10-03 20:46 UTC by ingawei

Getting rid of inline betting in embeds, replacing with quickbets
<img width="658" alt="Screen Shot 2022-10-03 at 1 45 33 PM" src="https://user-images.githubusercontent.com/46611122/193679156-841c2e70-a2a9-4444-9b51-d0a01b74da51.png">

logged out/not binary market view
<img width="659" alt="Screen Shot 2022-10-03 at 1 45 40 PM" src="https://user-images.githubusercontent.com/46611122/193679216-4b0710ec-5720-47aa-a7f7-4dfa4d259fac.png">

weird iframe border :( help

2022-10-03 20:47 UTC, ingawei commented
@akrolsmir need some help with figuring out if iFrame resizing is possible. Maybe we could talk about this in 1:1 tomorrow?

2022-10-04 22:37 UTC, jahooma commented
> @akrolsmir need some help with figuring out if iFrame resizing is possible. Maybe we could talk about this in 1:1 tomorrow?

I don't know if this would solve your problem, but you can measure the current iframe size with `useWindowSize()`

2022-10-04 23:28 UTC, jahooma requested changes
I think this change needs to be merged with Sinclair's change that shows the contract card on small iframe sizes.

I like this change overall! Quick bet arrows is better than having another custom UI for betting here.

2022-10-04 23:28 UTC, jahooma commented on web/pages/embed/[username]/[contractSlug].tsx
> +  if (user && (isBinary || isPseudoNumeric)) {
What if the market is closed or resolved? You would probably want the `else` case for that.

2023-11-16 00:53 UTC, closed without merging